pipeline {
    agent any

    environment {
        activeInstance = ''
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    // 기존 family-service가 실행 중인 경우 이를 activeInstance로 설정, 없으면 family-service를 기본값으로 사용
                    activeInstance = sh(script: "docker ps -a --filter 'name=backend/family-service' --format '{{.Names}}'", returnStdout: true).trim() ?: 'backend/family-service'
                }
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Deploy Family Service') {
            steps {
                withCredentials([file(credentialsId: 'family-application.yml', variable: 'application_yml')]) {
                    script {
                        // 활성화된 인스턴스를 기반으로 새로운 인스턴스 선택
                        def newInstance = (activeInstance == 'family-service') ? 'family-service-green' : 'family-service'

                        dir('backend/family-service') {
                            copyApplicationYaml(application_yml)
                            buildAndRunContainer(newInstance) // 내부 네트워크에서만 통신
                        }

                        // 새로운 인스턴스 실행 후 기존 인스턴스 삭제
                        stopAndRemoveContainer(activeInstance)

                        // 다음 배포를 위해 activeInstance 변수를 업데이트
                        activeInstance = newInstance
                    }
                }
            }
        }
    }
}

// 공통 함수: application.yml 복사
def copyApplicationYaml(application_yml) {
    sh 'mkdir -p src/main/resources'
    sh "cp ${application_yml} src/main/resources/application.yml"
}

// 공통 함수: 컨테이너 중지 및 삭제
def stopAndRemoveContainer(containerName) {
    def container = sh(script: "docker ps -a --filter 'name=${containerName}' --format '{{.ID}}'", returnStdout: true).trim()
    if (container) {
        sh "docker stop ${container}"
        sh "docker rm ${container}"
    }
}

// 공통 함수: 컨테이너 빌드 및 실행
def buildAndRunContainer(serviceName) {
    stopAndRemoveContainer(serviceName)
    sh 'chmod +x ./gradlew'
    sh './gradlew clean build -x test'
    sh "docker build -t ${serviceName} ."
    sh "docker run --name ${serviceName} -d ${serviceName}"
}
