pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Deploy Config Server') {
            when {
                changeset "backend/config-service/**"
            }
            steps {
                withCredentials([file(credentialsId: 'config-application.yml', variable: 'application_yml')]) {
                    script {
                        dir('backend/config-service') {
                            copyApplicationYaml(application_yml)
                            buildAndRunContainer('config-service', 8888)
                        }
                    }
                }
            }
        }

        stage('Build and Deploy Discovery Server') {
            when {
                changeset "backend/discovery-service/**"
            }
            steps {
                withCredentials([file(credentialsId: 'discovery-application.yml', variable: 'application_yml')]) {
                    script {
                        dir('backend/discovery-service') {
                            copyApplicationYaml(application_yml)
                            buildAndRunContainer('discovery-service', 8761)
                        }
                    }
                }
            }
        }

        stage('Build and Deploy API Gateway') {
            when {
                changeset "backend/api-gateway/**"
            }
            steps {
                withCredentials([file(credentialsId: 'api-gateway-application.yml', variable: 'application_yml')]) {
                    script {
                        dir('backend/api-gateway') {
                            copyApplicationYaml(application_yml)
                            buildAndRunContainer('api-gateway-service', 8000)
                        }
                    }
                }
            }
        }

        stage('Build and Deploy Classification Service') {
            steps {
                withCredentials([file(credentialsId: 'classification-service.env', variable: 'ENV_FILE')]) {
                    script {
                        dir('backend/classification-service') {
                            copyApplicationEnv(ENV_FILE)
                            buildAndRunContainerPython('classification-service')
                        }
                    }
                }
            }
        }
    }
}

// 공통 함수
def copyApplicationEnv(env) {
    sh "cp ${env} .env"
    sh "cat .env"
}

// 공통 함수: 컨테이너 중지 및 삭제
def stopAndRemoveContainer(containerName) {
    def container = sh(script: "docker ps -a --filter 'name=${containerName}' --format '{{.ID}}'", returnStdout: true).trim()
    if (container) {
        sh "docker stop ${container}"
        sh "docker rm ${container}"
    }
}

// 공통 함수: 컨테이너 빌드 및 실행
def buildAndRunContainerPython(serviceName) {
    stopAndRemoveContainer(serviceName)

    sh "docker build -t ${serviceName} ."
    sh "docker run --name ${serviceName} --env-file .env -p 5555:5555 -d ${serviceName}"
}

def buildAndRunContainer(serviceName, port) {
    stopAndRemoveContainer(serviceName)
    sh 'chmod +x ./gradlew'
    sh './gradlew clean build -x test'
    sh "docker build -t ${serviceName} ."
    sh "docker run --name ${serviceName} -d -p ${port}:${port} ${serviceName}"
}