pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Deploy Notification Service') {
            steps {
                withCredentials([file(credentialsId: 'notification-application.yml', variable: 'application_yml'),
                file(credentialsId: 'familring-firebase-key.json', variable: 'firebase_key')
                ]) {
                    script {
                        dir('backend/notification-service') {
                            copyApplicationYaml(application_yml)

                            // firebase key 추가
                            sh "cp ${firebase_key} src/main/resources/familring-firebase-key.json"

                            buildAndRunContainer('notification-service') // 내부 네트워크에서만 통신
                        }
                    }
                }
            }
        }
    }
}

// 공통 함수: application.yml 복사
def copyApplicationYaml(application_yml) {
    sh 'mkdir -p src/main/resources'
    sh "cp ${application_yml} src/main/resources/application.yml"
}

// 공통 함수: 컨테이너 중지 및 삭제
def stopAndRemoveContainer(containerName) {
    def container = sh(script: "docker ps -a --filter 'name=${containerName}' --format '{{.ID}}'", returnStdout: true).trim()
    if (container) {
        sh "docker stop ${containerName}"
        sh "docker rm ${containerName}"
    }
}

// 공통 함수: 컨테이너 빌드 및 실행
def buildAndRunContainer(serviceName) {
    stopAndRemoveContainer(serviceName)
    sh 'chmod +x ./gradlew'
    sh './gradlew clean build -x test'
    sh "docker build -t ${serviceName} ."
    sh "docker run --name ${serviceName} -d ${serviceName}"
}
