// Pipeline variable declaration with initial value set to the actual blue instance name
def activeInstance = ''

pipeline {
    agent any

    stages {
        stage('Initialize Active Instance') {
            steps {
                script {
                    // Check if 'timecapsule-service' is currently active; if so, set it as the activeInstance
                    activeInstance = sh(script: "docker ps --filter 'name=timecapsule-service' --format '{{.Names}}'", returnStdout: true).trim()

                    // If no active instance found, set activeInstance to 'timecapsule-service' by default
                    if (!activeInstance) {
                        activeInstance = 'timecapsule-service'
                    }
                }
            }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build and Deploy TimeCapsule Service') {
            steps {
                withCredentials([file(credentialsId: 'timecapsule-application.yml', variable: 'application_yml')]) {
                    script {
                        // Determine newInstance based on current active instance
                        def newInstance = (activeInstance == 'timecapsule-service') ? 'timecapsule-service-green' : 'timecapsule-service'

                        dir('backend/timecapsule-service') {
                            // If the active instance is not already running, build and run it
                            if (!isContainerRunning(activeInstance)) {
                                copyApplicationYaml(application_yml)
                                buildAndRunContainer(newInstance) // Run only in the internal network
                            } else {
                                echo "Using existing active instance: ${activeInstance}"
                            }
                        }

                        // If a new instance was created, stop and remove the old instance
                        if (activeInstance != newInstance) {
                            stopAndRemoveContainer(activeInstance)
                            activeInstance = newInstance
                        }
                    }
                }
            }
        }
    }
}

// Function to copy application.yml
def copyApplicationYaml(application_yml) {
    sh 'mkdir -p src/main/resources'
    sh "cp ${application_yml} src/main/resources/application.yml"
}

// Function to check if a container is running
def isContainerRunning(containerName) {
    def container = sh(script: "docker ps --filter 'name=${containerName}' --format '{{.ID}}'", returnStdout: true).trim()
    return container ? true : false
}

// Function to stop and remove container
def stopAndRemoveContainer(containerName) {
    def container = sh(script: "docker ps -a --filter 'name=${containerName}' --format '{{.ID}}'", returnStdout: true).trim()
    if (container) {
        sh "docker stop ${container}"
        sh "docker rm ${container}"
    }
}

// Function to build and run container
def buildAndRunContainer(serviceName) {
    stopAndRemoveContainer(serviceName)
    sh 'chmod +x ./gradlew'
    sh './gradlew clean build -x test'
    sh "docker build -t ${serviceName} ."
    sh "docker run --name ${serviceName} -d ${serviceName}"
}
