// 파이프라인 변수 선언 (초기 값 설정)
def activeInstance = 'calendar-service-blue'

pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Build and Deploy Calendar Service') {
            steps {
                withCredentials([file(credentialsId: 'calendar-application.yml', variable: 'application_yml')]) {
                    script {
                        // 활성화된 인스턴스를 기반으로 새로운 인스턴스 선택
                        def newInstance = (activeInstance == 'calendar-service-blue') ? 'calendar-service-green' : 'calendar-service-blue'

                        dir('backend/calendar-service') {
                            copyApplicationYaml(application_yml)
                            buildAndRunContainer(newInstance) // 내부 네트워크에서만 통신
                        }

                        // 다음 배포를 위해 activeInstance 변수를 업데이트
                        activeInstance = newInstance
                    }
                }
            }
        }
    }
}

// 공통 함수: application.yml 복사
def copyApplicationYaml(application_yml) {
    sh 'mkdir -p src/main/resources'
    sh "cp ${application_yml} src/main/resources/application.yml"
}

// 공통 함수: 컨테이너 중지 및 삭제
def stopAndRemoveContainer(containerName) {
    def container = sh(script: "docker ps -a --filter 'name=${containerName}' --format '{{.ID}}'", returnStdout: true).trim()
    if (container) {
        sh "docker stop ${container}"
        sh "docker rm ${container}"
    }
}

// 공통 함수: 컨테이너 빌드 및 실행
def buildAndRunContainer(serviceName) {
    stopAndRemoveContainer(serviceName)
    sh 'chmod +x ./gradlew'
    sh './gradlew clean build -x test'
    sh "docker build -t ${serviceName} ."
    sh "docker run --name ${serviceName} -d ${serviceName}"
}
